workflows:
  flutter-android:
    name: Build Flutter for Android
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Clean project
        script: flutter clean
      - name: Upgrade Android embedding
        script: flutter create .
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
